(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects)
	(:predicates
		(inserted) 
		(roll-x) 
		(stacked) 
		(roll-both) 
		(roll-y) 
		(roll-x2) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action act0
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype0 ?above) (objtype0 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.214 (roll-x)
				 0.029 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.757 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act1
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype0 ?above) (objtype0 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.010 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.105 (roll-x)
				 0.019 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.009 (roll-both)
				 0.043 (roll-y)
				 0.814 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act2
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype2 ?above) (objtype0 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.037 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.387 (roll-x)
				 0.150 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.426 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act3
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype2 ?above) (objtype0 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.094 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.117 (roll-x)
				 0.057 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.031 (roll-both)
				 0.012 (roll-y)
				 0.689 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act4
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype1 ?above) (objtype0 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.024 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.599 (roll-x)
				 0.145 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.231 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act5
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype1 ?above) (objtype0 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.201 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.268 (roll-x)
				 0.061 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.470 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act6
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype3 ?above) (objtype0 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.840 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.160 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act7
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype3 ?above) (objtype0 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.955 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.045 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act8
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype0 ?above) (objtype1 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.911 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.010 (roll-x)
				 0.079 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act9
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype2 ?above) (objtype1 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.936 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-x)
				 0.064 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act10
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype1 ?above) (objtype1 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.829 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-x)
				 0.171 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act11
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype3 ?above) (objtype1 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.854 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-x)
				 0.146 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act12
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype0 ?above) (objtype1 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.026 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.184 (roll-x)
				 0.790 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act13
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype2 ?above) (objtype1 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.061 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-x)
				 0.932 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.007 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act14
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype1 ?above) (objtype1 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.016 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-x)
				 0.984 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act15
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype3 ?above) (objtype1 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.010 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-x)
				 0.990 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act16
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype0 ?above) (objtype2 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.681 (roll-x)
				 0.144 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.175 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act17
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype0 ?above) (objtype2 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.466 (roll-x)
				 0.194 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.012 (roll-y)
				 0.328 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act18
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype2 ?above) (objtype2 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.005 (roll-x)
				 0.989 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.006 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act19
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype2 ?above) (objtype2 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.002 (roll-x)
				 0.888 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.110 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act20
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype1 ?above) (objtype2 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.005 (roll-x)
				 0.993 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.002 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act21
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype1 ?above) (objtype2 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-x)
				 1.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.000 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act22
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype3 ?above) (objtype2 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.024 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.976 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act23
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype3 ?above) (objtype2 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 1.000 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act24
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype0 ?above) (objtype3 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.877 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.056 (roll-both)
				 0.062 (roll-y)
				 0.005 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act25
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype1 ?above) (objtype3 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.002 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.242 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.686 (roll-both)
				 0.023 (roll-y)
				 0.047 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act26
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype2 ?above) (objtype3 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.020 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.297 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.451 (roll-both)
				 0.088 (roll-y)
				 0.144 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act27
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype3 ?above) (objtype3 ?below) (relation0 ?above ?below))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.722 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.278 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act28
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype0 ?above) (objtype3 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.010 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.119 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.138 (roll-both)
				 0.701 (roll-y)
				 0.032 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act29
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype2 ?above) (objtype3 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.193 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.041 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.515 (roll-both)
				 0.077 (roll-y)
				 0.173 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act30
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype1 ?above) (objtype3 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.058 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.015 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.511 (roll-both)
				 0.221 (roll-y)
				 0.195 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action act31
		:parameters (?above ?below)
		:precondition (and (pickloc ?above) (stackloc ?below) (objtype3 ?above) (objtype3 ?below) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.090 (roll-x)
				 0.000 (and (stacked) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll-both)
				 0.910 (roll-y)
				 0.000 (roll-x2))
				(not (pickloc ?above)))
	)
	(:action gainheight1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action gainheight2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action gainheight3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action gainheight4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action gainheight5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action gainheight6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action gainstack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action gainstack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action gainstack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action gainstack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action gainstack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action gainstack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
)
